### ISSUE TITLE
Problems importing via CSV

### ISSUE THREAD

**Issue by joshcanhelp** [SitanHuang/ledg#6]
I think I'm not quite understanding the concept represented in the CSV parser examples: 

https://github.com/SitanHuang/ledg/tree/develop/examples/csv

This might be a misunderstanding around double-entry but I can't seem to get what I think makes sense into something that is reported correctly. My CSVs look something like this:

```
10/28/21,2.47E+22,COMCAST CABLE COMM 800-COMCAST WA,800-COMCAST   WA ,-70,
9/11/21,2.47E+22,COVERCRAFT DIRECT 405-238-9651 OK,405-238-9651  OK ,-145.27,Expense.Josh
5/17/21,2.43E+22,COW CREEK RITZVILLE WA,RITZVILLE     WA ,-29.73,
```

... and my parser looks like this:

```js
delimeter = ",";
dateformat = "M/D/YY";
default_account = "Expense.Family";
bail = true;
skip(1);
process(() => {
  trim();
  add(
    date(col(1)),
    description(col(3)),
    cleared(),
    transfer(
      account(col(6),{}),
      amount(col(5))
    ),
    transfer(
      account("Asset.Bank.BankOfAmerica"),
      invert(amount(col(5)))
    )
  )
})
```

Date and description come through fine but all the expenses show up in the default account, even if I have a different one in the 6th column. I run that import and get something mysterious like:

```bash
Accounts                         Balance
Asset.Bank.BankOfAmerica       -1,022.10
Assets.Cash                            0
Expense.Family                  1,022.10
Expense.Josh                           0
Imbalance                              0
```

What am I doing wrong here? Is there some reading I need to do on this concept? 

Thank you!

**Comment by joshcanhelp** [comment]
I should mention, the CSV has many, many rows more than what I showed. Total is more than $1k even if everything was going to the right place.

**Comment by SitanHuang** [comment]
For your first comment, I altered the parser code to something like this:

```js
add(
    date(col(1)),
    description(col(3)),
    cleared(),
    transfer(
      account(col(6) || default_account), // if col 6 is empty, use default_account
      amount(col(5))
    ),
    transfer(
      account("Asset.Bank.BankOfAmerica"),
      invert(amount(col(5)))
    )
  )
```

And right now I don't see an immediate, obvious answer to why some rows had failed; it might require you to dig a little but as long as all rows are like these 3, which were succesfully imported with the above code, there shouldn't be any issues.

I've also uploaded another example parser to the repo.

Hopefully this helps!

**Comment by SitanHuang** [comment]
And the parser is just a piece of nodejs code so you have `console.log()` on your side!

**Comment by SitanHuang** [comment]
A new [commit](https://github.com/SitanHuang/ledg/commit/556fa159cd0d949e832ec176c1c4f065caaa1935) had been pushed to develop that allows `account(col(6))` to use default account if col 6 is empty.

**Comment by joshcanhelp** [comment]
This is great, thank you for taking the time to write all this out. I think part of this was not understanding some of the double-entry fundamentals. I don't know why it didn't occur to me to log anything to the console 🤦 so thanks for the reminder there!

Are all the global methods and properties we can use defined here?

https://github.com/SitanHuang/ledg/blob/develop/lib/core/csv/import.js

**Comment by SitanHuang** [comment]
> Are all the global methods and properties we can use defined here?
> 
> https://github.com/SitanHuang/ledg/blob/develop/lib/core/csv/import.js


Yes! Your parser is executed under the context of the `ctx` object so all of its variables and functions can be used.

**Comment by SitanHuang** [comment]
Closed due to inactivity.
